#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$BC_VER

url=https://github.com/gavinhoward/bc/archive/$version/bc-$version.tar.gz


fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	   
	#./configure --prefix=/usr           \
  #         --with-readline         \
  #          --mandir=/usr/share/man \
   #         --infodir=/usr/share/info

  PREFIX=/usr CC=gcc CFLAGS="-std=c99" ./configure.sh -G -O3        
	make
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
