#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$EUDEV_VER

url=https://dev.gentoo.org/~blueness/eudev/eudev-$version.tar.gz

fetch $url
fetch http://anduin.linuxfromscratch.org/LFS/udev-lfs-$UDEV_RULES_VER.tar.bz2

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	
#	cat > config.cache << "EOF"
#HAVE_BLKID=1
#BLKID_LIBS="-lblkid"
#BLKID_CFLAGS="-I/tools/include"
#EOF

	./configure --prefix=/usr           \
		    --bindir=/sbin          \
		    --sbindir=/sbin         \
		    --libdir=/usr/lib       \
		    --sysconfdir=/etc       \
		    --libexecdir=/lib       \
		    --with-rootprefix=      \
		    --with-rootlibdir=/lib  \
		    --enable-manpages       \
		    --disable-static        \
		    --config-cache
	LIBRARY_PATH=/tools/lib make
	mkdir -pv /lib/udev/rules.d
	mkdir -pv /etc/udev/rules.d
	make LD_LIBRARY_PATH=/tools/lib install

	tar -xvf $SOURCE_DIR/udev-lfs-$UDEV_RULES_VER.tar.bz2
	make -f udev-lfs-$UDEV_RULES_VER/Makefile.lfs install

	LD_LIBRARY_PATH=/tools/lib udevadm hwdb --update
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
