#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$GETTEXT_VER

url=http://ftp.gnu.org/gnu/gettext/gettext-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	./configure --prefix=/usr    \
		    --disable-static \
		    --docdir=/usr/share/doc/gettext-$version
	make
	make install
	chmod -v 0755 /usr/lib/preloadable_libintl.so
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
