#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$LIB_XCB_VER


url=https://xcb.freedesktop.org/dist/$name-$version.tar.gz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$name-$version.tar.gz -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {

      sed -i "s/pthread-stubs//" configure &&

      ./configure --prefix=/usr     \
                  --without-doxygen \
   make
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
