#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$OPENSSL_VER

url=https://openssl.org/source/openssl-$version.tar.gz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {

	sed -i '/\} data/s/ =.*$/;\n    memset(\&data, 0, sizeof(data));/' \
  		crypto/rand/rand_lib.c

	./config --prefix=/usr         \
		 --openssldir=/etc/ssl \
		 --libdir=lib          \
		 shared                \
		 zlib-dynamic
	make
	sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
	make MANSUFFIX=ssl install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
