#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$RUNIT_VER

url=http://smarden.org/runit/runit-$version.tar.gz

fetch $url

rm -fr $WORK_DIR/admin
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/admin/runit-$version
{ time \
   {
	package/compile
	
	cd command
	install -v runit runit-init /sbin
	install -v runsvdir runsv chpst svlogd sv /usr/bin
	install -v runsvchdir utmpset /usr/sbin
	cp -v ../man/* /usr/share/man/man8
	ln -svf /sbin/runit-init /sbin/init
	mkdir -pv /etc/sv
	mkdir -pv /etc/runit/runsvdir/single
	mkdir -pv /etc/runit/runsvdir/multi

   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/admin

registerpkg $(basename $0) $version

exit 0
