#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$LIB_INPUT_VER

url=https://www.freedesktop.org/software/libinput/libinput-$version.tar.xz
fetch $url

 rm -fr $WORK_DIR/$name-$version
 tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {

   	export XORG_PREFIX="/usr"
	export XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc \
    --localstatedir=/var --disable-static"

mkdir build 
cd    build 

meson --prefix=$XORG_PREFIX \
      -Dudev-dir=/lib/udev  \
      -Ddebug-gui=false     \
      -Dtests=false         \
      -Ddocumentation=false \
      -Dlibwacom=false      \
      ..                    
ninja

as_root()
{
  if   [ $EUID = 0 ];        then $*
  elif [ -x /usr/bin/sudo ]; then sudo $*
  else                            su -c \\"$*\\"
  fi
}

export -f as_root

as_root ninja install



   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
