#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$LLVM_VER

url=https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_PARENT_VER/llvm-$version.tar.xz
fetch $url

 rm -fr $WORK_DIR/$name-$version
 tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {

	mkdir -v build &&
	cd       build &&

	CC=gcc CXX=g++                                  \
	cmake -DCMAKE_INSTALL_PREFIX=/usr               \
	      -DLLVM_ENABLE_FFI=ON                      \
	      -DCMAKE_BUILD_TYPE=Release                \
	      -DLLVM_BUILD_LLVM_DYLIB=ON                \
	      -DLLVM_LINK_LLVM_DYLIB=ON                 \
	      -DLLVM_ENABLE_RTTI=ON                     \
	      -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
	      -DLLVM_BUILD_TESTS=ON                     \
	      -Wno-dev -G Ninja ..                      
	ninja
	ninja install

   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
