#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$XTERM_VER

url=http://invisible-mirror.net/archives/xterm/xterm-$version.tgz
fetch $url

 rm -fr $WORK_DIR/$name-$version
 tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {

   	export XORG_PREFIX="/usr"
	export XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc \
    --localstatedir=/var --disable-static"

	sed -i '/v0/{n;s/new:/new:kb=^?:/}' termcap 
	printf '\tkbs=\\177,\n' >> terminfo 

	TERMINFO=/usr/share/terminfo \
	./configure $XORG_CONFIG     \
	    --with-app-defaults=/etc/X11/app-defaults 

	make
	make install    
	make install-ti 

	mkdir -pv /usr/share/applications 
	cp -v *.desktop /usr/share/applications/

cat >> /etc/X11/app-defaults/XTerm << "EOF"
*VT100*locale: true
*VT100*faceName: Monospace
*VT100*faceSize: 10
*backarrowKeyIsErase: true
*ptyInitialErase: true
EOF


   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
