#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$INKSCAPE_VER

url=https://media.inkscape.org/dl/resources/file/inkscape-$version.tar.bz2

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
   	./autogen.sh
	./configure --prefix=/usr
	make
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$name-$version.log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $name $version

exit 0
