#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$SCREEN_VER

url=https://ftp.gnu.org/gnu/screen/screen-$version.tar.gz
fetch $url

 rm -fr $WORK_DIR/$name-$version
 tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {


	./configure --prefix=/usr                     \
	            --infodir=/usr/share/info         \
	            --mandir=/usr/share/man           \
	            --with-socket-dir=/run/screen     \
	            --with-pty-group=4                \
	            --with-sys-screenrc=/etc/screenrc 

	sed -i -e "s%/usr/local/etc/screenrc%/etc/screenrc%" {etc,doc}/* 
	make
	make install
	install -m 644 etc/etcscreenrc /etc/screenrc


   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
