#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=$SCROT_VER

url=https://github.com/dreamer/scrot/archive/scrot-$version.tar.gz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

mv $WORK_DIR/$name-$name-$version $WORK_DIR/$name-$version
cd $WORK_DIR/$name-$version
{ time \
   {
	./configure --prefix=/usr --disable-static
	make
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$name-$version.log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $name $version

exit 0
